[application]
asset_dir = "icons_windows"
name = "RatingPhysics"

[web.app]
title = "RatingPhysics"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "org.penakelex"
publisher = "penakelex"
icon = ["icons_windows/icon.ico", "icons_macos/icon.icns"]

[bundle.windows]
tsp = true
icon_path = "icons_windows/icon.ico"
allow_downgrades = true

[bundle.windows.webview_install_mode.OfflineInstaller]
silent = true
